# Generated by Django 4.2.19 on 2025-02-16 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('pet_name', models.CharField(blank=True, max_length=20, null=True)),
                ('post_type', models.IntegerField(choices=[(1, 'Se perdió mi mascota'), (2, 'Encontré una mascota perdida'), (3, 'Necesito ayuda con una mascota')])),
                ('other_area', models.CharField(blank=True, max_length=20, null=True)),
                ('post_message', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('post_img01', models.ImageField(upload_to='post_images/')),
                ('post_img02', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_img03', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_likes', models.IntegerField(default=0)),
                ('area', models.ManyToManyField(related_name='pet_area', to='petPosts.area')),
                ('pet_color', models.ManyToManyField(related_name='pet_colors', to='petPosts.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
