# Generated by Django 4.2.19 on 2025-02-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area']},
        ),
    ]
