# Generated by Django 4.2.19 on 2025-02-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0002_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petpost',
            options={'ordering': ['-post_date', '-post_likes']},
        ),
    ]
