# Generated by Django 4.2.19 on 2025-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0003_alter_petpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'Se perdió mi mascota'), (2, 'Encontré una mascota perdida'), (3, 'Doy mascota en tránsito/adopción'), (4, 'Quiero adoptar/transitar una mascota'), (5, 'Necesito ayuda con una mascota')]),
        ),
    ]
