# Generated by Django 4.2.19 on 2025-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0004_alter_petpost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='petpost',
            name='other_pet_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='other_pet_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='pet_type',
            field=models.ManyToManyField(related_name='pet_types', to='petPosts.pettype'),
        ),
    ]
