# Generated by Django 4.2.19 on 2025-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0005_pettype_alter_color_options_petpost_other_pet_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pettype',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='petpost',
            name='pet_qty',
            field=models.IntegerField(default=1),
        ),
    ]
