# Generated by Django 4.2.19 on 2025-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0006_alter_color_options_alter_pettype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='area',
            field=models.ManyToManyField(default='ROSARIO', related_name='pet_area', to='petPosts.area'),
        ),
    ]
