# Generated by Django 4.2.19 on 2025-02-24 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petPosts', '0007_alter_petpost_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='post_title',
            field=models.CharField(default='URGENTE! SE MUDARON Y LOS DEJARON. SE BUSCA TRANSITO O ADOPCION. CONTACTO 3471518522', max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
